version: '3.3'

services:
  ezxssweb:
    container_name: ezxssweb
    build: ./php
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./www:/var/www/html
    depends_on:
      - ezxssdb

  ezxssdb:
    container_name: ezxssdb
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=waitalone.cn
      - MYSQL_DATABASE=ezxss
    volumes:
      - ./ezxssdb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: ezxssdb
      PMA_PORT: 3306
    depends_on:
      - ezxssdb